### ISSUE TITLE
Can we not use Session?

### ISSUE THREAD

**Issue by Chun-Yang** [poetic/react-autoform-material-ui#1]
Can we use other methods, like reactive var or reactive dict, instead of Session?
There is a possibility that developers use the same Session key in their application.

BTW, awesome job :+1:

**Comment by JohnRodney** [comment]
+1

**Comment by codeNgamer** [comment]
@Chun-Yang Thanks, I'm actually refactoring at the moment. The new push should have significant changes as well as not using sessions.

**Comment by codeNgamer** [comment]
@Chun-Yang react-autoform-material-ui now uses a global error object to maintain error states across all forms
