### ISSUE TITLE
Errors while adding package

### ISSUE THREAD

**Issue by flake** [poetic/react-autoform-material-ui#4]
> While checking for poetic:react-autoform-material-ui@0.0.7:
> error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by codeNgamer** [comment]
@flake Hey sorry about that, it appears the last push to atmosphere somehow got corrupted. Updating the package should fix that now.

**Comment by flake** [comment]
@codeNgamer thank you :)

**Comment by codeNgamer** [comment]
@flake no worries man. i'll be closing this issue now
