### ISSUE TITLE
Issue with Date and select option

### ISSUE THREAD

**Issue by Akash-dvd** [poetic/react-autoform-material-ui#5]
In date  the  date.jsx file has incorrent template name at line 73
Select option is not being captured

**Comment by codeNgamer** [comment]
@Akash-dvd apologies, hadn't gotten around to implementing that. this issue should be fixed in update 0.0.9. getting on #6 now

**Comment by Akash-dvd** [comment]
Ok .. Thanks

**Comment by codeNgamer** [comment]
@Akash-dvd No problem, closing this now
