### ISSUE TITLE
Array And Object fields

### ISSUE THREAD

**Issue by Akash-dvd** [poetic/react-autoform-material-ui#6]
Quickform is not rendering arrays and object fields in schema.

**Comment by codeNgamer** [comment]
@Akash-dvd arrays and object fields should render now in version 0.1.0; Quick note however, arrays do not support add and remove buttons yet. please confirm that this issue is resolved for you

**Comment by Akash-dvd** [comment]
Ok ... Is there ETA for 0.1,0

**Comment by codeNgamer** [comment]
@Akash-dvd That's pushed out already. Updating the package should give you that version

**Comment by codeNgamer** [comment]
@Akash-dvd Hey, can you let me know if that all worked out for you so I can close this issue.
