### ISSUE TITLE
Consider basing on izzilab:material-ui?

### ISSUE THREAD

**Issue by snickell** [poetic/react-autoform-material-ui#7]
This package is really cool, and something that I definitely need.... but I'm a little concerned about basing on poetic:material-ui instead of the more commonly used izzilab:material-ui: it seems like in the long term if there are (hopefully) more material-ui based atmosphere packages having a divergent upstream source will force picking between one material-ui ecosystem or another.

Any suggestions or ways I could help with this? Are your material-ui package and izzilabs widely divergent or pretty similar?

**Comment by snickell** [comment]
(and sorry if this is a stupid question, I'm a complete beginner here, and I understand there are often very good reasons for starting a new package!)

**Comment by JohnRodney** [comment]
@snickell I would say the main differences between poetic material-ui and izzilab:material-ui is poetic's contains a sample app example, and a test to make sure that the package loaded properly.  Ultimately I think the choice for using our own package on this was so we could control all the versions and not have anything upstream breaking the package.

From looking at the repos of both I don't see any difference in functionality between the two.  It looks like we use a different namespace in the poetic package than they do as well.  

Sorry about late response on this and we appreciate the feedback.  @codeNgamer if I missed anything here don't hesitate to add to the conversation ;o).

**Comment by JohnRodney** [comment]
Since this isn't an open issue with the repo I'm going to close but feel free to ping me or codeNgamer if you have any further questions.

**Comment by codeNgamer** [comment]
@snickell Hey sorry for the late reply and thanks for the support. It's just as @JohnRodney  said, poetic:material-ui was created in part to provide react for the community and also in whole as a foundation for poetic:react-autoform-material-ui. This decision was made in order to mitigate any problems which might arise from an external dependency.
